version: "3"
services:
  redis:
    image: redis:alpine
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PERMISSION_HOST: redis
    volumes:
      - .:/code
    links:
      - redis

